#!/bin/bash

# Change the owner of all files and directories in the current working directory to "vincent"
find . -exec chown vincent {} \;

# Change the group owner of all files and directories in the current working directory to "staff"
find . -exec chgrp staff {} \;

